import { Alert, Pressable, StyleSheet, Switch, Text, View } from "react-native";
import { router } from "expo-router";
import { useState } from "react";
import { ScreenContainer } from "@/components/screen-container";
import { useAuth } from "@/hooks/use-auth";
import { trpc } from "@/lib/trpc";
import { cancelGentleReminders, requestGentleReminderPermission, scheduleGentleReminder } from "@/lib/notifications";

export default function SettingsScreen() {
  const { user, logout } = useAuth();
  const [reminder, setReminder] = useState(true);
  const updateReminder = trpc.notifications.setGentleReminder.useMutation();
  const deleteAllData = trpc.privacy.deleteAllData.useMutation();
  const toggle = async (next: boolean) => { setReminder(next); try { if (next && !(await requestGentleReminderPermission())) throw new Error("denied"); await updateReminder.mutateAsync({ enabled: next }); if (next) await scheduleGentleReminder(); else await cancelGentleReminders(); } catch { setReminder(!next); Alert.alert("暫時未能更新", "請在系統設定容許通知，或者稍後再試。") } };
  const signOut = async () => { await logout(); router.replace("/login" as never); };
  const confirmDelete = () => Alert.alert("刪除帳戶及資料？", "雲端的練習紀錄、音域範圍與提醒設定會永久刪除，而且無法復原。", [{ text: "取消", style: "cancel" }, { text: "確認刪除", style: "destructive", onPress: async () => { try { await deleteAllData.mutateAsync(); await cancelGentleReminders(); await signOut(); } catch { Alert.alert("暫時未能刪除", "請稍後再試。") } } }]);
  return <ScreenContainer className="px-5"><View style={styles.page}><Text style={styles.eyebrow}>設定</Text><Text style={styles.title}>照顧練習，{`\n`}亦照顧自己。</Text><View style={styles.profile}><View style={styles.avatar}><Text style={styles.avatarText}>{user?.name?.slice(0, 1) ?? "聲"}</Text></View><View><Text style={styles.name}>{user?.name ?? "練吓聲用戶"}</Text><Text style={styles.email}>{user?.email ?? "已登入帳戶"}</Text></View></View><Text style={styles.section}>練習提醒</Text><View style={styles.row}><View style={styles.rowCopy}><Text style={styles.rowTitle}>溫和提示</Text><Text style={styles.rowBody}>停咗幾日未練，先至提醒你返嚟。</Text></View><Switch value={reminder} onValueChange={toggle} trackColor={{ false: "#E7D9C6", true: "#F4AAA3" }} thumbColor={reminder ? "#EF6257" : "#FFF9F0"} /></View><Text style={styles.section}>資料與帳戶</Text><Pressable style={styles.row} onPress={() => Alert.alert("資料私隱", "我們只會同步練習紀錄、音域範圍和進度；不會保存原始錄音。") }><View style={styles.rowCopy}><Text style={styles.rowTitle}>我的資料</Text><Text style={styles.rowBody}>查看同步與私隱做法。</Text></View><Text style={styles.chevron}>›</Text></Pressable><Pressable style={[styles.row, styles.dangerRow]} onPress={confirmDelete}><View style={styles.rowCopy}><Text style={[styles.rowTitle, styles.danger]}>刪除帳戶及資料</Text><Text style={styles.rowBody}>永久刪除雲端練習紀錄。</Text></View><Text style={[styles.chevron, styles.danger]}>›</Text></Pressable><Pressable onPress={signOut} style={styles.signOut}><Text style={styles.signOutText}>登出</Text></Pressable></View></ScreenContainer>;
}
const styles = StyleSheet.create({ page: { flex: 1, paddingTop: 18, gap: 16 }, eyebrow: { color: "#EF6257", fontSize: 14, fontWeight: "800", letterSpacing: 1 }, title: { color: "#172B4D", fontWeight: "800", fontSize: 31, lineHeight: 39, letterSpacing: -0.6 }, profile: { flexDirection: "row", alignItems: "center", gap: 13, paddingVertical: 12 }, avatar: { height: 46, width: 46, borderRadius: 23, backgroundColor: "#172B4D", alignItems: "center", justifyContent: "center" }, avatarText: { color: "#FFF9F0", fontWeight: "800", fontSize: 17 }, name: { color: "#172B4D", fontSize: 16, fontWeight: "800" }, email: { color: "#62718A", fontSize: 13, marginTop: 2 }, section: { color: "#62718A", fontWeight: "800", fontSize: 13, marginTop: 10, letterSpacing: 0.4 }, row: { minHeight: 74, backgroundColor: "#FFF9F0", borderRadius: 17, borderWidth: 1, borderColor: "#E7D9C6", padding: 16, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 18 }, rowCopy: { flex: 1 }, rowTitle: { color: "#172B4D", fontSize: 15, fontWeight: "800" }, rowBody: { color: "#62718A", fontSize: 12, lineHeight: 18, marginTop: 3 }, chevron: { fontSize: 28, color: "#62718A", lineHeight: 28 }, dangerRow: { borderColor: "#F1C1BA" }, danger: { color: "#C44842" }, signOut: { alignItems: "center", padding: 14, marginTop: "auto" }, signOutText: { color: "#C44842", fontSize: 15, fontWeight: "800" } });
